# Cann't keep this empty

AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # This is input_size and we have used VGG 16 model 
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01