# This section is to download different type of files of the link
artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/entbappy/Branching-tutorial/raw/master/cat-dog-data.zip
  local_data_files: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion